import type { MarketplaceStats } from '@student-rental/contracts';
import { useQuery } from '@tanstack/react-query';
import { router } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Screen } from '@/components/Screen';
import { LoadingView } from '@/components/StateView';
import { apiRequest } from '@/lib/api';
import { colors, radius, spacing } from '@/theme';

export default function AdminTab() { const stats = useQuery({ queryKey: ['admin-stats'], queryFn: () => apiRequest<{ stats: MarketplaceStats }>('/admin/stats', {}, true) }); if (stats.isLoading || !stats.data) return <LoadingView label="Loading marketplace health..." />; const value = stats.data.stats; return <Screen><Text style={styles.title}>Marketplace control</Text><View style={styles.grid}><Stat label="Active properties" value={value.activeProperties} /><Stat label="Available units" value={value.availableUnits} /><Stat label="Pending review" value={value.pendingListings} alert={value.pendingListings > 0} /><Stat label="Open reports" value={value.openReports} alert={value.openReports > 0} /><Stat label="Contact actions" value={value.contactActions} /><Stat label="Stale units" value={value.staleUnits} alert={value.staleUnits > 0} /></View><Nav title="Review listings" subtitle="Approve, request changes, reject or verify" onPress={() => router.push('/admin/listings')} /><Nav title="Resolve reports" subtitle="Investigate inaccurate and fraudulent listings" onPress={() => router.push('/admin/reports')} /><Nav title="Manage universities" subtitle="Coordinates, radius and active discovery areas" onPress={() => router.push('/admin/universities')} /><Nav title="Manage users" subtitle="Review roles and suspend abusive accounts" onPress={() => router.push('/admin/users')} /></Screen>; }
function Stat({ label, value, alert }: { label: string; value: number; alert?: boolean }) { return <View style={[styles.stat, alert && styles.alert]}><Text style={styles.value}>{value}</Text><Text style={styles.label}>{label}</Text></View>; }
function Nav({ title, subtitle, onPress }: { title: string; subtitle: string; onPress: () => void }) { return <Pressable style={styles.nav} onPress={onPress}><View style={{ flex: 1 }}><Text style={styles.navTitle}>{title}</Text><Text style={styles.navSub}>{subtitle}</Text></View><Text style={styles.arrow}>›</Text></Pressable>; }
const styles = StyleSheet.create({ title: { color: colors.ink, fontSize: 29, fontWeight: '900' }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, stat: { width: '48%', backgroundColor: colors.surface, padding: spacing.md, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border }, alert: { borderColor: colors.warning, backgroundColor: '#FFF8E8' }, value: { color: colors.primary, fontSize: 25, fontWeight: '900' }, label: { color: colors.muted }, nav: { flexDirection: 'row', alignItems: 'center', padding: spacing.md, backgroundColor: colors.surface, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border }, navTitle: { color: colors.ink, fontWeight: '900', fontSize: 16 }, navSub: { color: colors.muted, marginTop: 3 }, arrow: { color: colors.primary, fontSize: 30 } });

