import type { OwnerDashboard, PropertyDetails } from '@student-rental/contracts';
import { useQuery } from '@tanstack/react-query';
import { router } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { AppButton } from '@/components/AppButton';
import { Badge } from '@/components/Badge';
import { Screen } from '@/components/Screen';
import { EmptyView, LoadingView } from '@/components/StateView';
import { apiRequest } from '@/lib/api';
import { titleCase } from '@/lib/format';
import { useSession } from '@/store/session';
import { colors, radius, spacing } from '@/theme';

export default function PropertiesTab() { const user = useSession((state) => state.user); const dashboard = useQuery({ queryKey: ['owner-dashboard'], queryFn: () => apiRequest<{ dashboard: OwnerDashboard }>('/dashboard/owner', {}, true), enabled: user?.role === 'LANDLORD' || user?.role === 'AGENT' }); const properties = useQuery({ queryKey: ['my-properties'], queryFn: () => apiRequest<{ items: PropertyDetails[] }>('/properties/mine', {}, true), enabled: user?.role === 'LANDLORD' || user?.role === 'AGENT' }); if (!user) return <EmptyView title="Sign in to list homes" message="Landlord and agent tools require an account." actionLabel="Sign in" onAction={() => router.push('/auth/sign-in')} />; if (dashboard.isLoading || properties.isLoading) return <LoadingView label="Loading your properties..." />; const stats = dashboard.data?.dashboard; return <Screen><View style={styles.header}><View><Text style={styles.title}>Your properties</Text><Text style={styles.subtitle}>Keep every unit's availability current.</Text></View><AppButton label="Add" onPress={() => router.push('/owner/property-form')} /></View>{stats ? <View style={styles.stats}><Stat label="Properties" value={stats.properties} /><Stat label="Available" value={stats.availableUnits} /><Stat label="Inquiries" value={stats.inquiries} /><Stat label="Confirm now" value={stats.confirmationNeededUnits} /></View> : null}{properties.data?.items.length ? properties.data.items.map((property) => <Pressable key={property.id} style={styles.card} onPress={() => router.push(`/owner/property/${property.id}`)}><View style={{ flex: 1 }}><Text style={styles.name}>{property.name}</Text><Text style={styles.meta}>{property.neighbourhood} · {property.units.length} unit(s)</Text></View><Badge label={titleCase(property.status)} color={property.status === 'ACTIVE' ? colors.success : colors.warning} /></Pressable>) : <EmptyView title="No property yet" message="Create the building first, then add its individual rooms or studios." actionLabel="Add property" onAction={() => router.push('/owner/property-form')} />}</Screen>; }
function Stat({ label, value }: { label: string; value: number }) { return <View style={styles.stat}><Text style={styles.statValue}>{value}</Text><Text style={styles.statLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.md }, title: { color: colors.ink, fontSize: 27, fontWeight: '900' }, subtitle: { color: colors.muted, marginTop: 3 }, stats: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, stat: { width: '48%', backgroundColor: colors.surface, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, padding: spacing.md }, statValue: { color: colors.primary, fontWeight: '900', fontSize: 24 }, statLabel: { color: colors.muted }, card: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, backgroundColor: colors.surface, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, padding: spacing.md }, name: { color: colors.ink, fontWeight: '900', fontSize: 16 }, meta: { color: colors.muted, marginTop: 4 } });

