import type { UserRole } from '@student-rental/contracts';
import { router } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { AppButton } from '@/components/AppButton';
import { AppTextField } from '@/components/AppTextField';
import { Screen } from '@/components/Screen';
import { useSession } from '@/store/session';
import { titleCase } from '@/lib/format';
import { colors, radius, spacing } from '@/theme';

export default function RegisterScreen() { const register = useSession((state) => state.register); const [form, setForm] = useState({ firstName: '', lastName: '', email: '', phone: '+237', password: '', role: 'STUDENT' as Exclude<UserRole, 'ADMIN'> }); const [loading, setLoading] = useState(false); const submit = async () => { if (!form.firstName || !form.lastName || !form.password || (!form.email && form.phone === '+237')) return Alert.alert('Missing information', 'Complete your name, an email or phone number, and password.'); try { setLoading(true); const user = await register({ ...form, email: form.email || undefined, phone: form.phone === '+237' ? undefined : form.phone }); router.dismissAll(); router.replace(user.role === 'STUDENT' ? '/(tabs)/home' : '/(tabs)/properties'); } catch (error) { Alert.alert('Could not create account', error instanceof Error ? error.message : 'Please try again.'); } finally { setLoading(false); } }; return <Screen><Text style={styles.title}>Create your account</Text><View style={styles.roles}>{(['STUDENT', 'LANDLORD', 'AGENT'] as const).map((role) => <Pressable key={role} style={[styles.role, form.role === role && styles.active]} onPress={() => setForm({ ...form, role })}><Text style={[styles.roleText, form.role === role && styles.activeText]}>{titleCase(role)}</Text></Pressable>)}</View><AppTextField label="First name" value={form.firstName} onChangeText={(firstName) => setForm({ ...form, firstName })} /><AppTextField label="Last name" value={form.lastName} onChangeText={(lastName) => setForm({ ...form, lastName })} /><AppTextField label="Email (optional if phone supplied)" value={form.email} onChangeText={(email) => setForm({ ...form, email })} keyboardType="email-address" autoCapitalize="none" /><AppTextField label="Phone" value={form.phone} onChangeText={(phone) => setForm({ ...form, phone })} keyboardType="phone-pad" /><AppTextField label="Password (at least 8 characters)" value={form.password} onChangeText={(password) => setForm({ ...form, password })} secureTextEntry /><AppButton label="Create account" loading={loading} onPress={() => void submit()} /></Screen>; }
const styles = StyleSheet.create({ title: { color: colors.ink, fontSize: 29, fontWeight: '900' }, roles: { flexDirection: 'row', gap: spacing.sm }, role: { flex: 1, padding: spacing.sm, alignItems: 'center', backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md }, active: { backgroundColor: colors.primary, borderColor: colors.primary }, roleText: { color: colors.ink, fontWeight: '700', fontSize: 12 }, activeText: { color: colors.surface } });

