import { router } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text } from 'react-native';
import { AppButton } from '@/components/AppButton';
import { AppTextField } from '@/components/AppTextField';
import { Screen } from '@/components/Screen';
import { useSession } from '@/store/session';
import { colors, spacing } from '@/theme';

export default function SignInScreen() { const signIn = useSession((state) => state.signIn); const [identity, setIdentity] = useState('student@demo.cm'); const [password, setPassword] = useState('Demo123!'); const [loading, setLoading] = useState(false); const submit = async () => { try { setLoading(true); const user = await signIn(identity.trim(), password); router.dismissAll(); router.replace(user.role === 'ADMIN' ? '/(tabs)/admin' : user.role === 'LANDLORD' || user.role === 'AGENT' ? '/(tabs)/properties' : '/(tabs)/home'); } catch (error) { Alert.alert('Unable to sign in', error instanceof Error ? error.message : 'Please try again.'); } finally { setLoading(false); } }; return <Screen contentStyle={styles.content}><Text style={styles.title}>Welcome back</Text><Text style={styles.subtitle}>Use your email address or Cameroon phone number.</Text><AppTextField label="Email or phone" value={identity} onChangeText={setIdentity} autoCapitalize="none" keyboardType="email-address" /><AppTextField label="Password" value={password} onChangeText={setPassword} secureTextEntry /><AppButton label="Sign in" loading={loading} onPress={() => void submit()} /><Pressable onPress={() => router.push('/auth/otp')}><Text style={styles.link}>Sign in with a one-time code</Text></Pressable><Pressable onPress={() => router.push('/auth/register')}><Text style={styles.link}>New here? Create an account</Text></Pressable><Text style={styles.demo}>Demo accounts: student@demo.cm, landlord@demo.cm, agent@demo.cm, admin@demo.cm · Password: Demo123!</Text></Screen>; }
const styles = StyleSheet.create({ content: { flexGrow: 1, justifyContent: 'center', padding: spacing.lg }, title: { color: colors.ink, fontSize: 31, fontWeight: '900' }, subtitle: { color: colors.muted, marginBottom: spacing.md }, link: { color: colors.primary, fontWeight: '800', textAlign: 'center', padding: spacing.sm }, demo: { color: colors.muted, fontSize: 12, lineHeight: 18, textAlign: 'center', marginTop: spacing.lg } });
